### ISSUE TITLE
缺少mermain.js文件

### ISSUE THREAD

**Issue by fangInFBI** [LinWanCen/draw-graph#2]
idea版本2023.3，使用插件的时候提示缺少mermain.js，应该怎么解决

**Comment by LinWanCen** [comment]
在 [https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.js]( https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.js) 下载后放在如下任一目录：

C:/Users/Public/draw-graph/mermaid.js

D:/draw-graph/mermaid.js

Applications/draw-graph/mermaid.js

**Comment by LinWanCen** [comment]
理论上应该会自己把插件内嵌的 mermaid.js 放到目录中，不知道是否权限问题，可以提供一些信息给到我这边研究下。

前阵子车祸住院回复晚了不好意思。
