### ISSUE TITLE
没有任何反应

### ISSUE THREAD

**Issue by suhengli** [LinWanCen/draw-graph#3]
idea 2023.2.3，使用没有任何效果，没有任何反应不管是 Java 类还是 pom 文件

**Comment by LinWanCen** [comment]
右击文件选调用图试试看

**Comment by suhengli** [comment]
jcef（内嵌谷歌 chrome 浏览器）未加载，请重启 IDE！
重启几次了，就是没有效果，还是提示这个。在安装插件的项目 A 中使用，没有任何效果，在其他项目打开是有效果的

**Comment by suhengli** [comment]
如果是在已打开 idea 就所在的项目则使用不了，如果此时打开其他项目，是可以的，在其他项目可以用

**Comment by LinWanCen** [comment]
哈哈哈，我发现修复这个问题的版本我没发市场，市场上那个版本要手动把侧边栏开启后才有效果。

**Comment by suhengli** [comment]
请问什么时候发市场呢？

**Comment by LinWanCen** [comment]
最近事情比较多，上次写的代码没整理，其实还有一些功能想做的，应该过一阵子后会更新一些新功能
[draw-graph-1.01.2023.10.27_07.37.zip](https://github.com/LinWanCen/draw-graph/files/13183619/draw-graph-1.01.2023.10.27_07.37.zip)

**Comment by suhengli** [comment]
好的，不着急，你慢慢来。希望后续可以增加放大、导出之类的功能，如果调用非常多，那个图片根本看不了，虽然可以复制源码自己弄一个 HTML 文件，但终归还是不那么方便

**Comment by LinWanCen** [comment]
插件市场通过了刚提交的新版本，增加了文件按钮可以打开生成的文件，建议比较大的图用浏览器看。
被公司选来北京总部交流，最近晚上又重构补充了很多功能，pom 的嵌套解析和 kotlin 语言解析两个功能比较烧脑，后面再慢慢改。
