### ISSUE TITLE
【建议】加入 class 的注释选项

### ISSUE THREAD

**Issue by trivita** [LinWanCen/draw-graph#6]
现在只有方法的注释
puml 的图里面可以也加上类的注释

**Comment by LinWanCen** [comment]
你类上的注释是怎么样的，可能是注释不规范，目前没有提供 Show Comment 插件那种兼容不规范注释的设置

**Comment by trivita** [comment]
> 你类上的注释是怎么样的，可能是注释不规范，目前没有提供 Show Comment 插件那种兼容不规范注释的设置

是不太规范，我 close 问题

顺便问一句，有没有考虑把 nomnoml 加入可视化的方案？
